# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='pictures', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
