# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170531_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', validators=[myapp.validators.validate_file_extension], verbose_name='Изображение'),
        ),
    ]
